# How to use AppVeyor to build a multi-arch Docker image for Linux and Windows
# https://stefanscherer.github.io/use-appveyor-to-build-multi-arch-docker-image/
#
# Building ASP.NET Core apps on both Windows and Linux using AppVeyor
# https://andrewlock.net/building-asp-net-core-apps-on-both-windows-and-linux-using-appveyor/
#
# appveyor.yml Example:
# https://github.com/cdcseacave/openMVS/blob/master/.appveyor.yml

version: '{build}'
image:
  - Visual Studio 2017
  - Ubuntu2004
build: false
clone_depth: 50
branches:
  except:
    - travis-ci
    - gh-pages

environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true

for:
  -
    #------------------
    # Windows
    #------------------
    matrix:
      only:
        - image: Visual Studio 2017
    init:
      - ps: "ls 'C:/Program Files/Java/jdk*'"
      - ps: "ls 'C:/Program Files (x86)/Java/jdk*'"
      - cmd: set MAVEN_OPTS=-Xmx768m -XX:MaxPermSize=128m -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2
      - cmd: set JAVA_OPTS=-Xmx768m -XX:MaxPermSize=128m
    install:
      - cmd: echo JAVA_HOME=%JAVA_HOME%, HOMEPATH=%HOMEPATH%, PATH=%PATH%
      - cmd: ./mvnw.cmd --version

    test_script:
      # test under java 8
      - cmd: set JAVA_HOME=C:\Program Files\Java\jdk1.8.0
      - ./mvnw.cmd clean install --batch-mode --no-transfer-progress
      # test under java 11
      - cmd: set JAVA_HOME=C:\Program Files\Java\jdk11
      - ./mvnw.cmd clean install --batch-mode --no-transfer-progress

    after_test:
      - ps: Remove-Item -r -fo C:\Users\appveyor\.m2\repository\com\alibaba\dns-cache-manipulator*

    cache:
      - C:\Users\appveyor\.m2\
  -
    #------------------
    # Ubuntu
    #------------------
    matrix:
      only:
        - image: Ubuntu2004
    init:
      - sh: export MAVEN_OPTS="-Xmx768m -XX:MaxPermSize=128m -Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2"
      - sh: export JAVA_OPTS="-Xmx768m -XX:MaxPermSize=128m"

    test_script:
      - sh: ./scripts/integration-test.sh

    after_test:
      - sh: ./scripts/codecov.sh
      - sh: rm -rf /home/appveyor/.m2/repository/com/alibaba/dns-cache-manipulator*

    cache:
      - /home/appveyor/.m2/
      - /home/appveyor/.sdkman/
